### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by MiriamPeskowitz** [learn-co-curriculum/js-rails-as-api-rendering-different-content-types-using-rails#4]
Hi, loving the new js lessons and labs. 

Can this paragraph be made a little more clear? There's a lot going on, maybe break it down into steps, or re-order. I think step 1 is to type in the console 'open example_frontend.html' -- and then Replace with the code above. Then start the rails server. I don't think we've worked before (too much) with the idea of a file that doesn't appear in the files but shows up on screen -- and it would be kind of great to be able to see where this file actually is. Thanks for considering! 

![Screen Shot 2019-10-06 at 8 15 33 PM](https://user-images.githubusercontent.com/18649892/66278351-2b321c00-e876-11e9-8c45-94db7095eb01.png)

From the lesson:
This isn't very fancy, but this is actually enough for us to start using our JavaScript skills and access with a fetch() request. To check this out yourself, in this code-along, there is an HTML file, example_frontend.html. Replace BirdsController with the code above, start up the Rails server and open example_frontend.html. From the browser's console, with the Rails server running, run the following:

**Comment by maxwellbenton** [comment]
Hi @MiriamPeskowitz,

Thank you for providing this feedback. We've updated the instructions around using the example frontend, converting it into steps with the code required and noting where the file is located, which should resolve this issue. 

Thank you for contributing! We're glad you are loving the new JS materials!

**Comment by MiriamPeskowitz** [comment]
Thanks, it's really smart and well conceived, it must have taken such hard
work and thoughtfulness to put it together.
