### ISSUE TITLE
Edit text

### ISSUE THREAD

**Issue by MiriamPeskowitz** [learn-co-curriculum/js-rails-as-api-rendering-different-content-types-using-rails#5]
Hi, this sentence seems like it may be missing a few words: 

To render JSON from a Rails controller, you specify json: followed something can be converted to valid JSON:

Should it be " followed BY something THAT can be converted....

**Comment by maxwellbenton** [comment]
Hi @MiriamPeskowitz,

Fixed! Thank you for letting us know about these errors!
